### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by techdragon** [AlyHKafoury/Operator-rs#1]
Would it be possible to select and include a clear license (open source or otherwise) for this code so that other developers are able to legally use it?

**Comment by AlyHKafoury** [comment]
Sure I will add a license to it

**Comment by flipbit03** [comment]
This issue can be closed now. Thanks @AlyHKafoury for making this MIT-licensed!

**Comment by AlyHKafoury** [comment]
> This issue can be closed now. Thanks @AlyHKafoury for making this MIT-licensed!

You are welcome
